### ISSUE TITLE
ReactiveVar is undefined

### ISSUE THREAD

**Issue by ratacibernetica** [kuka/autoform-reactive-froala#2]
I'm getting "Uncaught ReferenceError: ReactiveVar is not defined", at afReactiveFroala.js:14 ,
any advice?

Also, i noticed that you have to declare type "reactiveFroala" instead "froalaEditor".

**Comment by ratacibernetica** [comment]
Nevermind, had missing a package called reactive-var, got fixed adding it:

 meteor add reactive-var

Thanks!

**Comment by kuka** [comment]
Hey @ratacibernetica , now it’s added to package itself. Thanks!
